export const actions = {
  CHANGE_TITLE: 'CHANGE_TITLE',
  TITLE_LOWERCASE: 'TITLE_LOWERCASE',
  TITLE_UPPERCASE: 'TITLE_UPPERCASE',
  CHANGE_INVERT: 'INVERT_TITLE',
  RESTORE: 'RESTORE',
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',
};
